[project]
name = "portscanner"
version = "0.7.1"
description = "Asynchronous Port Scanner"
requires-python = ">=3.10,<4.0"
authors = [{ name = "GoodiesHQ", email = "aarcher73k@gmail.com" }]
dependencies = [
  "aiodns (>=4.0.4,<5.0.0)",
  "colorama>=0.4.6,<1.0",
]

[project.scripts]
portscanner = "portscanner.__main__:run"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
black = "^26.5.1"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"